dist:
    trusty

language:
    generic

sudo:
    required

group:
    travis_latest

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq curl git grep pcregrep sed
    - sudo pip install bashate

script:
    - sudo bash ./main.sh -t

matrix:
    fast_finish:   true

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
    webhooks:      https://www.travisbuddy.com/
